# Base Settings
species_1: "Human"
species_2: "Mouse"
organ_1: "Pancreas"
organ_2: "Liver"
temp_dir: "/ocean/projects/bio230007p/can1/temp"

# HALPER Settings
halper_script: "/ocean/projects/bio230007p/can1/halLiftover-postprocessing/halper_map_peak_orthologs.sh"
hal_file: "/ocean/projects/bio230007p/ikaplow/Alignments/10plusway-master.hal"
halper_output_dir: "/ocean/projects/bio230007p/can1/output/halper"
species_1_organ_1_peak_file: "/ocean/projects/bio230007p/can1/s2_v2/human_pancreas.idr.optimal_peak.narrowPeak"
species_1_organ_2_peak_file: "/ocean/projects/bio230007p/can1/s2_v2/human_liver.idr.optimal_peak.narrowPeak"
species_2_organ_1_peak_file: "/ocean/projects/bio230007p/can1/s2_v2/mouse_pancreas.idr.optimal_peak.narrowPeak"
species_2_organ_2_peak_file: "/ocean/projects/bio230007p/can1/s2_v2/mouse_liver.idr.optimal_peak.narrowPeak"

# Enhancers vs promoters pipeline Settings
species_1_TSS_file: "/ocean/projects/bio230007p/ikaplow/HumanGenomeInfo/gencode.v27.annotation.protTranscript.TSSsWithStrand_sorted.bed"
species_2_TSS_file: "/ocean/projects/bio230007p/ikaplow/MouseGenomeInfo/gencode.vM15.annotation.protTranscript.geneNames_TSSWithStrand_sorted.bed"

# Bedtool preprocess Settings
bedtool_preprocess_output_dir: "/ocean/projects/bio230007p/can1/output/bedtool_preprocess"

# Cross-species ortholog open vs closed pipeline Settings
cross_species_open_vs_closed_output_dir: "/ocean/projects/bio230007p/can1/output/cross_species_open_vs_closed"

# Cross-tissues region shared vs specific pipeline Settings
cross_tissues_shared_vs_specific_output_dir: "/ocean/projects/bio230007p/can1/output/cross_tissues_shared_vs_specific"

# Within-species enhancers vs promoters pipeline Settings
cross_tissues_enhancers_vs_promoters_output_dir: "/ocean/projects/bio230007p/can1/output/cross_tissues_enhancers_vs_promoters"

# Cross-species enhancers vs promoters pipeline Settings
cross_species_enhancers_vs_promoters_output_dir: "/ocean/projects/bio230007p/can1/output/cross_species_enhancers_vs_promoters"

# The following fields will be automatically generated by the pipeline
# Normally, you don't need to specify these fields

# These are the paths to the files that contain the HALPER output
# They should be under the halper_output_dir
# species_1_organ_1_to_species_2: ".../...Halper.narrowPeak.gz"
# species_1_organ_2_to_species_2: ".../...Halper.narrowPeak.gz"
# species_2_organ_1_to_species_1: ".../...Halper.narrowPeak.gz"
# species_2_organ_2_to_species_1: ".../...Halper.narrowPeak.gz"